package com.ayproductions.appinventor.extensions.graphicsandmultimedia.mumedia;

import android.Manifest;
import android.app.Activity;
import android.content.Context;
import com.google.appinventor.components.annotations.*;
import com.google.appinventor.components.common.ComponentCategory;
import com.google.appinventor.components.runtime.AndroidNonvisibleComponent;
import com.google.appinventor.components.runtime.ComponentContainer;
import com.google.appinventor.components.runtime.EventDispatcher;
import android.graphics.Bitmap;
import android.media.MediaPlayer;
import android.os.Bundle;
import android.os.Environment;
import android.widget.Toast;

@DesignerComponent(
        version = 1,
        description = "Multimedia Extension",
        category = ComponentCategory.EXTENSION,
        nonVisible = true,
        iconName = "")

@SimpleObject(external = true)
//Libraries
@UsesLibraries(libraries = "")
//Permissions
@UsesPermissions(permissionNames = "")

public class MuMedia extends AndroidNonvisibleComponent {

    //Activity and Context
    private Context context;
    private Activity activity;

    public MuMedia(ComponentContainer container){
        super(container.$form());
        this.activity = container.$context();
        this.context = container.$context();
    }

    @SimpleFunction(description = "Sample Function Generated by Niotron")
    public void TestFunction(){

    }

    @SimpleEvent(description = "Test Event Generated by Niotron")
    public void TestEvent(){
        EventDispatcher.dispatchEvent(this, "TestEvent");
    }
}
